#!/bin/bash

# NAME: Collin Prince
# ID: 505091865
# EMAIL: cprince99@g.ucla.edu


#standard
for x in 1 2 3 4 5 6 7 8 9 10 11 12
do  
    for y in 1 10 100 1000 10000 100000
    do
	./lab2_add --threads=$x --iterations=$y
    done
done


#lab2_add-1.png
for x in 2 4 8 12
do
    for y in 10 20 40 80 100 250 500 750 1000 10000 100000
    do
	./lab2_add --threads=$x --iterations=$y --yield
    done
done


#lab2_add-2.png -- no yield
for x in 2 3 4 5 6 7 8
do
    for y in 10 100 1000 10000 100000
    do
	./lab2_add --threads=$x --iterations=$y
    done
done

#lab2_add-2.png -- yield
for x in 2 3 4 5 6 7 8
do
    for y in 100 1000 10000 100000
    do
	./lab2_add --threads=$x --iterations=$y --yield
    done
done


#lab2_add-4.png -- sync options m and c
for x in 2 4 8 12
do
    for y in 10 100 1000 10000
    do
	for z in "m" "c"
	do
	    ./lab2_add --threads=$x --iterations=$y --sync=$z --yield
	done
    done
done


#lab2_add-4.png --sync option s
for x in 2 4 8 12
do
    for y in 10 100 1000
    do
	./lab2_add --threads=$x --iterations=$y --sync=s --yield
    done
done

#lab2_add-5.png
for x in 1 2 4 8 12
do
    for y in 1 10 100 1000 10000
    do
	for z in "m" "c" "s"
	do
	    ./lab2_add --threads=$x --iterations=$y --sync=$z
	done
    done
done




# lab2_list tests


#lab2_list-1.png
for x in 1 10 100 1000 10000 20000
do
    ./lab2_list --iterations=$x
done

#lab2_list-2.png
for x in 2 4 8 12
do
    for y in 1 10 100 1000
    do
	./lab2_list --threads=$x --iterations=$y
    done
done

#lab2_list-2.png
for x in 2 4 8 12
do
    for y in 1 2 4 8 16 32
    do
	for z in "i" "d" "id" "il" "dl" "idl"
	do
	    ./lab2_list --threads=$x --iterations=$y --yield=$z
	done
    done
done



for x in 1 2 4 6 8 10 12
do
    for y in 2 4 8 16 32
    do
	for z in "m" "s"
	do
	    for a in "i" "d" "l" "id" "il" "dl" "idl"
	    do
		./lab2_list --threads=$x --iterations=$y --sync=$z --yield=$a
	    done
	done
    done
done


#lab2_list-4.png
for x in 1 2 3 4 5 6 7 8 9 12 16 24
do
    for y in "m" "s"
    do
	./lab2_list --threads=$x --iterations=1000 --sync=$y
    done
done

