# NAME: Collin Prince, Thilan Tran
# EMAIL: cprince99@g.ucla.edu, thilanoftran@gmail.com
# ID: 505091865, 605140530

.PHONY: dist clean

lab3b:
	ln -s lab3b.py lab3b
	chmod u+x lab3b

dist:
	tar -czvf lab3b-505091865.tar.gz lab3b.py README Makefile

clean:
	rm -f lab3b lab3b-505091865.tar.gz
